import express from "express";
import { CreateSalesController } from "../controller/sales/createSales.controller";
import { GetAllSalesProductController } from "../controller/sales/getSales.controller";
import { updateSalesProductController } from "../controller/sales/updateSales.controller";
import getProductById from "../controller/sales/getSalesById.controller";
export const SalesProductRouter = express.Router();
SalesProductRouter.get("/", GetAllSalesProductController);
SalesProductRouter.post("/", CreateSalesController);
SalesProductRouter.put("/:selectedId", updateSalesProductController);
SalesProductRouter.get("/:selectedId", getProductById);
